### ISSUE TITLE
Visual Studio/isalnum throws exception on non-ascii chars

### ISSUE THREAD

**Issue by kungfooman** [ioquake/ioq3#393] opened 2018-12-13 07:00 UTC
In q_shared.c is this macro:

```C
#define Q_IsColorString(p)	((p) && *(p) == Q_COLOR_ESCAPE && *((p)+1) && isalnum(*((p)+1))) // ^[0-9a-zA-Z]
```

When entering some non-ascii text in console like `^°` Visual Studio throws an exception in debug mode, which is pretty annoying.

I just converted that macro to a function definition and added this function to q_shared.c:

```C
qboolean Q_IsColorString(const char *p) {
	if (!p)
		return qfalse;

	if (*(p) != Q_COLOR_ESCAPE)
		return qfalse;

	if (*((p)+1) == 0)
		return qfalse;

	if (*((p)+1) <= 0 || *((p)+1) >= 255)
		return qfalse;

	if (isalnum(*(p + 1)) == 0)
		return qfalse;

	return qtrue;
}
```

**Comment by ensiform** [comment] 2018-12-13 15:05
Issue with visual studio

**Comment by ensiform** [comment] 2018-12-13 15:46
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/isalnum-iswalnum-isalnum-l-iswalnum-l?view=vs-2017

**Comment by timangus** [comment] 2018-12-13 15:56
Well exactly: "The behavior of isalnum and _isalnum_l is undefined if c is not EOF or in the range 0 through 0xFF". The question is, does the ioq3 code make such calls?

**Comment by ensiform** [comment] 2018-12-13 17:04
Well the check right above it looks for that range so IDK why it would get further, however, because it's not unsigned, maybe that's the issue.

**Comment by timangus** [comment] 2018-12-13 17:20
What checks the range? The macro doesn't check the range.

**Comment by ensiform** [comment] 2018-12-13 20:36
Oh I was looking at his code

**Comment by estabroo** [comment] 2018-12-13 21:00
The range check is irrelevant and incorrect anyway.  A char is -128 to 127 and unsigned char is already 0 to 255 and can't be outside that range.

**Comment by timangus** [comment] 2018-12-13 21:19
Hence my question about if the macro is expanded on a value which has a type wider than char...

**Comment by ensiform** [comment] 2018-12-13 21:37
Q3 doesn't support extended text anywhere in networking so it's kind of not really an issue here, plus, this seems to be expected behavior in Visual Studio debug mode..

**Comment by kungfooman** [comment] 2018-12-13 22:40
@ensiform network chars don't matter, I just type on my local keyboard and it crashes, e.g. `shift+^` results in `°` (ascii code -80)

@estabroo before you claim something is wrong please read the documentation of `isalnum`

@timangus i can confirm, this happens all the time to me when testing debug builds, probably because of the keyboard layout, when I open/close console via `shift+esc` and sometimes my finger isn't pressing `esc` but `^` (which is below `esc`), then it adds the `°` char, which is ascii value of `-80`.

And since `-80` is not representable as `unsigned char` it asserts:

![isalnum_exception](https://user-images.githubusercontent.com/5236548/49971549-2e4acd00-ff2f-11e8-819c-5f563ecd6881.png)

One can argue if `eof` (`-1`) should be range checked aswell, but I just made it accept the range `0 - 255`, `-1` or `eof` is simply no color value in Q3

**Comment by timangus** [comment] 2018-12-13 23:35
You need to get a backtrace and figure out what is causing c to be out of range, because that is a bug that should be fixed. Replacing the macro with your function solves the issue, but hides the underlying cause.

**Comment by kungfooman** [comment] 2018-12-14 00:07
![backtrace](https://user-images.githubusercontent.com/5236548/49974809-57715a80-ff3b-11e8-8002-ab50ac6fcaa4.png)

It pretty much boiles down to negative ascii values  like `-80`, which is valid in my understanding. Its just the `isalnum` convention which expects the `-1 to 255` range.

Another solution would probably be to disallow negative keyboard input chars, but I would rather just check the range right before `isalnum`

**Comment by timangus** [comment] 2018-12-14 00:15
Ah yes, chars are signed, duh. OK, make a PR for your function and I'll commit it. You don't need to surround p in parentheses.

**Comment by estabroo** [comment] 2018-12-14 00:35
Apologies kungfooman, my comment was only directed at that if statement, the function is passed in a char pointer, that makes that if statement incorrect as the max value is 127 so it can't come close to 255.  The "negative" ascii values are just 128-255 mapped with 2s complement, so with a char pointer parameter there is some value in the if, if you want to eliminate those.  If the function were switched to an unsigned char pointer then it'd already be 0 to 255, no need to check.

**Comment by kungfooman** [comment] 2018-12-14 01:50
@estabroo thanks, I considered that for the code in the PR

@timangus I removed all parantheses now, using `[]` C sugar syntax

**Closed** 2018-12-14 10:00 UTC
