### ISSUE TITLE
Opengl2 Renderer Issues (Dark Models & Sound Issues)

### ISSUE THREAD

**Issue by myleg123** [ioquake/ioq3#331] opened 2017-12-15 03:58 UTC
When I use the opengl2 renderer, on some maps the models are almost completely black. https://i.gyazo.com/0f6c10e42be4cee3bdbcac03cc4361bb.jpg 
The gun model is almost entirely black. When I use the opengl1 renderer, this issue doesn't happen. https://i.gyazo.com/ef8c1c3af38f44c17ece1fbd60160645.jpg 
Also, when I use the opengl2 renderer, for whatever reason, an audible popping sound occurs when a loud or sudden noise happens, such as a rocket being launched.

**Comment by ensiform** [comment] 2017-12-15 14:25
Sound issues won't be related to the renderer being used.

Are you using up to date test build with newest SDL2 2.0.7 ?

Which OS?

**Comment by myleg123** [comment] 2017-12-15 20:57
I am using Windows 10, and I don't know what version of SDL2 I am using, but it is 950,272 bytes large and its MD5 hash is 391c8b3713cbb952a822248c5c2fde9d

**Comment by zturtleman** [comment] 2017-12-15 21:25
That's SDL 2.0.4 (SDL2.dll, x86). That is what ioquake3 ships with the test builds. The SDL version is listed somewhere in the File Properties by the way.

The OpenGL2 renderer's lighting isn't identical to OpenGL1. I think settings like r_hdr 1 and r_autoExposure 1 (both set by default) may increase brightness/darkness contrast. The gun in the OpenGL1 renderer screenshot is nearly black so this just seems like a minor lighting difference. Try r_hdr 0 and r_autoExposure 0.

What map are the screenshots of?

**Comment by myleg123** [comment] 2017-12-15 22:40
A rather obscure map called Pillcity ws.q3df.org/map/pillcity/

**Comment by KuehnhammerTobias** [comment] 2017-12-15 22:42
@myleg123  Iirc the specific map was compiled with some additional grid size parameters, probably 256x256 or something (to reduce compile time and memory usage). Most of the such high grid size parameterstime  will produce dark models, another reason of dark models could be that the map is somehow at a bad angle, or compiled with a very old q3map map compiler.
In any case I think this is not a renderer bug, it's a map related bug (or feature). Unfortunately you can't do much to already compiled maps :(
As zturtleman already said the OpenGL2 renderer's lighting isn't identical to OpenGL1. OpenGL2 is a bit 'darker'.
@zturtleman: the map is called piLLciTy made by piLL: https://ws.q3df.org/map/pillcity/

**Comment by KuehnhammerTobias** [comment] 2017-12-15 22:49
@myleg123: I did a quick check, as I said, the map is even compiled with "gridsize" "1024 1024 1024"'! This is definitely too much.

**Comment by myleg123** [comment] 2017-12-15 23:02
@zturtleman I tried your solutions, and, well, https://i.gyazo.com/825202e2feab18db8ba782dc7c32ac1e.jpg
It obviously wasn't like this before, and even when I changed those 2 cvars back to default, I still get this problem. I switched back to opengl1, and I don't have this problem. Any guesses?

**Comment by zturtleman** [comment] 2017-12-15 23:56
Uh, I don't know what happened in that screenshot. From the ammo box it looks like it's using wrong images or shaders. Maybe try vid_restart?

The black first person gun is caused by the opengl2 renderer disabling the extra ambient light when r_hdr is enabled. This is fixed in 7c2dd01873f4f1762368639869899229f071427a. The [test build](https://ioquake3.org/get-it/test-builds/) will probably be updated in an hour.

**Comment by myleg123** [comment] 2017-12-16 01:43
So now the test build download link for both windows versions is dead. 
https://i.gyazo.com/c97825fbbc28addbf20af145aec66db5.png
Once the link works, I will try the new build.

**Comment by myleg123** [comment] 2017-12-16 03:15
I tried vid_restart, but to no avail. However, it did fix the player head model.

**Comment by myleg123** [comment] 2017-12-16 15:47
Download link still doesn't work...

**Comment by ensiform** [comment] 2017-12-16 16:24
Honestly the newest screenshot looks like artifacts caused by driver or gpu.

**Comment by myleg123** [comment] 2017-12-16 20:13
So I deleted the q3config file to reset all possible changed cvars, and I don't get that issue that is shown in that screenshot anymore. If I had to guess, I think it's the cvar changes in the cvars section at the bottom of this page that caused it. https://github.com/ioquake/ioq3/blob/master/opengl2-readme.md I changed them along with the r_hdr and r_autoExposure changes.

**Comment by myleg123** [comment] 2017-12-16 20:17
I retried your 2 fixes without those other changes, and it worked! https://i.gyazo.com/502e5189b747f4a2636e2ffc2fd1625a.jpg
For those cvars on that opengl2-readme.md page, they are, without a doubt, the thing that caused it.

**Closed** 2018-02-04 12:41 UTC
